language: python

services:
- postgresql

python:
- '3.6'

before_install:
- openssl aes-256-cbc -K $encrypted_123b787db187_key -iv $encrypted_123b787db187_iv -in .ssh/locuszoom-db.enc -out .ssh/locuszoom-db -d

install:
- ssh-agent bash -c 'ssh-add .ssh/locuszoom-db; git clone git@github.com:statgen/locuszoom-db.git lzdb'
- pip install pytest psycopg2-binary
- cd lzdb/db/pytest
- python pytest-initdb.py --host 127.0.0.1 --port 5432 --user postgres --connect-db postgres --database pytest

script:
- pytest
